version: '3.1'
services:
  nginx:
    build:
      context: "./nginx"
      dockerfile: "Dockerfile"
    environment:
      - "HOSTNAME=api:8080"
    depends_on:
      - "api"
    networks:
      - "network-nodejs"
    ports:
      - "8080:80"

  redis:
    image: "redis:alpine"

  postgres:
    image: "postgres"
    container_name: "postgres"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "qwertyuiop"
      POSTGRES_DB: "DatabaseName"
      PGDATA: "/data/postgres"
    depends_on:
      - "redis"
    networks:
      - "network-db"

  api:
    build:
      context: "../"
      dockerfile: "docker/api/Dockerfile"
    container_name: "nodejs"
    environment:
      - "NODE_ENV=production"
    networks:
      - "network-db"
      - "network-nodejs"

networks:
  network-db:
  network-nodejs: